spring.application.name=AccademiJava

# --- CONFIGURAZIONE DATABASE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/adozioni?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURAZIONE EMAIL (GMAIL) ---
# Sostituisci 'tua-email@gmail.com' con la tua vera mail
# Sostituisci 'le-tue-16-lettere' con la Password per le App di Google
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuo-indirizzo@gmail.com
spring.mail.password=le-tue-16-lettere-senza-spazi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.test-connection=true

# --- SICUREZZA ---
spring.security.user.name=admin
spring.security.user.password=admin
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970