spring.application.name=AccademiJava

# Configurazione Database con SCHEMA ESPLICITO
# Aggiungiamo ?currentSchema=public per evitare che Java cerchi altrove
spring.datasource.url=jdbc:postgresql://localhost:5432/adozioni?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate
# Mostriamo le query SQL (true) per vedere cosa succede nella console di IntelliJ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sicurezza Base
spring.security.user.name=admin
spring.security.user.password=admin

# JWT Configurazione
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970